package br.com.unesa.view;

import br.com.unesa.controller.ClienteController;
import br.com.unesa.model.Cliente;
//import br.com.unesa.model.Fisico;
//import br.com.unesa.model.Juridico;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Amanda Dias
 * @author Abraão Barreiros
 * @brief Classe view
 * @date 23/11/2020
 */
public class Tela extends javax.swing.JFrame {
    
    ClienteController controller = new ClienteController();
    private List<Cliente> lista = null;
    Cliente cliente = new Cliente();
    //Fisico fisico = new Fisico();
    //Juridico juridico = new Juridico();
    private final DefaultListModel<String> model = new DefaultListModel<>();
    
    
    private void carregarLista(){
        model.removeAllElements();
        lista = controller.ObterTodos();
        lista.forEach((cliente) -> {
            model.addElement("Id: "+cliente.getId()+" | Nome: "+cliente.getNome()
                    +" | Endereço: "+cliente.getEndereco()+" | E-mail: "+cliente.getEmail()
                    +" | Tipo: "+cliente.getTipo() + " | CPF: "+cliente.getCpf()
                    +" | CNPJ: "+cliente.getCnpj()+" | RG: "
                    +cliente.getRg()+" | Insc. Estadual: "
                    +cliente.getInscEstadual());
        });
    }
    
    /**
     * Creates new form Tela
     */
    public Tela() throws HeadlessException {
        initComponents();
        carregarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbRg = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        rbFisico = new javax.swing.JRadioButton();
        rbJuridico = new javax.swing.JRadioButton();
        tfCpf = new javax.swing.JTextField();
        tfRg = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        lbCnpj = new javax.swing.JLabel();
        lbInscEstadual = new javax.swing.JLabel();
        tfCnpj = new javax.swing.JTextField();
        tfInscEstadual = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCliente = new javax.swing.JList<>();
        btExcluir = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfBusca = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taExibeBusca = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lbIdEditar = new javax.swing.JLabel();
        lbEdicaoCliente = new javax.swing.JLabel();
        btAtualizar = new javax.swing.JButton();
        lbIdValor = new javax.swing.JLabel();
        lbNomeEditar = new javax.swing.JLabel();
        tfNomeEditar = new javax.swing.JTextField();
        lbEnderecoEditar = new javax.swing.JLabel();
        tfEnderecoEditar = new javax.swing.JTextField();
        lbEmailEditar = new javax.swing.JLabel();
        tfEmailEditar = new javax.swing.JTextField();
        lbTipoEditar = new javax.swing.JLabel();
        rbFisicoEditar = new javax.swing.JRadioButton();
        rbJuridicoEditar = new javax.swing.JRadioButton();
        tfCpfEditar = new javax.swing.JTextField();
        lbCpfEditar = new javax.swing.JLabel();
        lbRgEditar = new javax.swing.JLabel();
        tfRgEditar = new javax.swing.JTextField();
        lbCnpjEditar = new javax.swing.JLabel();
        tfCnpjEditar = new javax.swing.JTextField();
        lbInscEstadualEditar = new javax.swing.JLabel();
        tfInscEstadualEditar = new javax.swing.JTextField();

        jMenu5.setText("jMenu5");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("CADASTRO");

        lbEndereco.setText("Endereço:");

        lbNome.setText("Nome:");

        lbEmail.setText("E-mail:");

        lbTipo.setText("Tipo:");

        lbCpf.setText("CPF:");

        lbRg.setText("RG:");

        rbFisico.setText("Fisico");
        rbFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFisicoActionPerformed(evt);
            }
        });

        rbJuridico.setText("Juridico");
        rbJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuridicoActionPerformed(evt);
            }
        });

        btCadastrar.setForeground(new java.awt.Color(102, 153, 255));
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        lbCnpj.setText("CNPJ:");

        lbInscEstadual.setText("Insc. Estadual:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome)
                    .addComponent(lbEndereco)
                    .addComponent(lbTipo)
                    .addComponent(lbCpf)
                    .addComponent(lbRg)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbFisico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbJuridico))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbInscEstadual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbCnpj)
                                        .addGap(73, 73, 73)
                                        .addComponent(tfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(963, 963, 963))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btCadastrar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(rbFisico)
                    .addComponent(rbJuridico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpf)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCnpj)
                    .addComponent(tfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRg)
                    .addComponent(lbInscEstadual)
                    .addComponent(tfInscEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btCadastrar)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 153, 255));
        jLabel2.setText("CLIENTES");

        lstCliente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCliente.setModel(model);
        jScrollPane2.setViewportView(lstCliente);

        btExcluir.setForeground(new java.awt.Color(102, 153, 255));
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btEditar.setForeground(new java.awt.Color(102, 153, 255));
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("Selecione um cliente para:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btEditar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Buscar por Id");

        btBuscar.setForeground(new java.awt.Color(102, 153, 255));
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        taExibeBusca.setColumns(20);
        taExibeBusca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        taExibeBusca.setRows(5);
        jScrollPane1.setViewportView(taExibeBusca);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscar)
                                .addGap(38, 38, 38))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel3)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Buscar", jPanel3);

        lbIdEditar.setText("Id:");

        lbEdicaoCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbEdicaoCliente.setForeground(new java.awt.Color(102, 153, 255));
        lbEdicaoCliente.setText("ATUALIZAÇÃO");

        btAtualizar.setForeground(new java.awt.Color(102, 153, 255));
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        lbIdValor.setText("0");

        lbNomeEditar.setText("Nome:");

        lbEnderecoEditar.setText("Endereço:");

        lbEmailEditar.setText("E-mail:");

        lbTipoEditar.setText("Tipo:");

        rbFisicoEditar.setText("Fisico");
        rbFisicoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFisicoEditarActionPerformed(evt);
            }
        });

        rbJuridicoEditar.setText("Juridico");
        rbJuridicoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuridicoEditarActionPerformed(evt);
            }
        });

        lbCpfEditar.setText("CPF:");

        lbRgEditar.setText("RG:");

        lbCnpjEditar.setText("CNPJ:");

        lbInscEstadualEditar.setText("Insc. Estadual:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeEditar)
                            .addComponent(lbEnderecoEditar)
                            .addComponent(lbTipoEditar)
                            .addComponent(lbCpfEditar)
                            .addComponent(lbRgEditar)
                            .addComponent(lbEmailEditar)
                            .addComponent(lbIdEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfEnderecoEditar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEmailEditar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(rbFisicoEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbJuridicoEditar))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfRgEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lbInscEstadualEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfInscEstadualEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lbCnpjEditar)
                                        .addGap(73, 73, 73)
                                        .addComponent(tfCnpjEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(tfNomeEditar)
                            .addComponent(lbIdValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(lbEdicaoCliente))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbEdicaoCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdEditar)
                    .addComponent(lbIdValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeEditar)
                    .addComponent(tfNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoEditar)
                    .addComponent(tfEnderecoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailEditar)
                    .addComponent(tfEmailEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoEditar)
                    .addComponent(rbFisicoEditar)
                    .addComponent(rbJuridicoEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCpfEditar)
                    .addComponent(tfCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCnpjEditar)
                    .addComponent(tfCnpjEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRgEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRgEditar)
                    .addComponent(lbInscEstadualEditar)
                    .addComponent(tfInscEstadualEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btAtualizar)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Editar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

        cliente.setNome(tfNome.getText());
        cliente.setEndereco(tfEndereco.getText());
        cliente.setEmail(tfEmail.getText());
        if (rbFisico.isSelected()) {
            cliente.setTipo("F");
        } else {
            cliente.setTipo("J");
        }
        cliente.setCpf(tfCpf.getText());
        cliente.setRg(tfRg.getText());
        cliente.setCnpj(tfCnpj.getText());
        cliente.setInscEstadual(tfInscEstadual.getText());
        controller.incluir(cliente);
        /*
        if (rbFisico.isSelected()) {
            fisico.setNome(tfNome.getText());
            fisico.setEndereco(tfEndereco.getText());
            fisico.setEmail(tfEmail.getText());
            fisico.setTipo("F");
            fisico.setCpf(tfCpf.getText());
            fisico.setRg(tfRg.getText());
            controller.incluir(fisico);
        } else if (rbJuridico.isSelected()) {
            juridico.setNome(tfNome.getText());
            juridico.setEndereco(tfEndereco.getText());
            juridico.setEmail(tfEmail.getText());
            juridico.setTipo("J");
            juridico.setCnpj(tfCnpj.getText());
            juridico.setInscEstadual(tfInscEstadual.getText());
            controller.incluir(juridico);    
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um tipo!");
        }   
        */
        carregarLista();
        limpar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void rbJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJuridicoActionPerformed

    private void rbFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFisicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFisicoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (lstCliente.getSelectedValue() != null){
            int resp = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o cliente "
                    +lista.get(lstCliente.getSelectedIndex()).getNome()+ "?");
            if(resp == JOptionPane.YES_OPTION){
                controller.excluir(lista.get(lstCliente.getSelectedIndex()).getId());
                carregarLista();
            }
        }    
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        Cliente cliente = new Cliente();
        cliente = controller.buscar(Integer.parseInt(tfBusca.getText()));
        tfBusca.setText("");
        taExibeBusca.setText(cliente.toString());
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        try {
            Cliente cliente = new Cliente();
            int id = lista.get(lstCliente.getSelectedIndex()).getId();
            cliente = controller.buscar(id);
            paginaEdita(cliente);
            this.jTabbedPane1.setSelectedIndex(3);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "erro"+e);
        } 
    }//GEN-LAST:event_btEditarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        
        cliente.setNome(tfNome.getText());
        cliente.setEndereco(tfEndereco.getText());
        cliente.setEmail(tfEmail.getText());
        if (rbFisico.isSelected()) {
            cliente.setTipo("F");
        } else if (rbJuridico.isSelected()){
            cliente.setTipo("J");
        }
        cliente.setCpf(tfCpf.getText());
        cliente.setRg(tfRg.getText());
        cliente.setCnpj(tfCnpj.getText());
        cliente.setInscEstadual(tfInscEstadual.getText());
        controller.atualizar(cliente);
        
        carregarLista();
        limpar();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void rbFisicoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFisicoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFisicoEditarActionPerformed

    private void rbJuridicoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuridicoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbJuridicoEditarActionPerformed

    private void paginaEdita(Cliente cliente){
        this.lbIdValor.setText(Integer.toString(cliente.getId()));
        this.tfNomeEditar.setText(cliente.getNome());
        this.tfEnderecoEditar.setText(cliente.getEndereco());
        this.tfEmailEditar.setText(cliente.getEmail());
        if (cliente.getTipo().equals("F")){
            this.rbFisicoEditar.setSelected(true);
        }else if (cliente.getTipo().equals("J")) {
            this.rbJuridicoEditar.setSelected(true);
        } else {
            this.rbFisicoEditar.setSelected(false);
            this.rbJuridicoEditar.setSelected(false);
        }
        this.tfCpfEditar.setText(cliente.getCpf());
        this.tfRgEditar.setText(cliente.getRg());
        this.tfCnpjEditar.setText(cliente.getCnpj());
        this.tfInscEstadualEditar.setText(cliente.getInscEstadual()); 
    }
    
    private void limpar(){
        lbIdValor.setText("0");
        tfNome.setText("");
        tfEndereco.setText("");
        tfEmail.setText("");
        rbFisico.setSelected(false);
        rbJuridico.setSelected(false);
        tfCpf.setText("");
        tfRg.setText("");
        tfCnpj.setText("");
        tfInscEstadual.setText("");
    }
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCnpj;
    private javax.swing.JLabel lbCnpjEditar;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbCpfEditar;
    private javax.swing.JLabel lbEdicaoCliente;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailEditar;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEnderecoEditar;
    private javax.swing.JLabel lbIdEditar;
    private javax.swing.JLabel lbIdValor;
    private javax.swing.JLabel lbInscEstadual;
    private javax.swing.JLabel lbInscEstadualEditar;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeEditar;
    private javax.swing.JLabel lbRg;
    private javax.swing.JLabel lbRgEditar;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipoEditar;
    private javax.swing.JList<String> lstCliente;
    private javax.swing.JRadioButton rbFisico;
    private javax.swing.JRadioButton rbFisicoEditar;
    private javax.swing.JRadioButton rbJuridico;
    private javax.swing.JRadioButton rbJuridicoEditar;
    private javax.swing.JTextArea taExibeBusca;
    private javax.swing.JTextField tfBusca;
    private javax.swing.JTextField tfCnpj;
    private javax.swing.JTextField tfCnpjEditar;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfCpfEditar;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailEditar;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfEnderecoEditar;
    private javax.swing.JTextField tfInscEstadual;
    private javax.swing.JTextField tfInscEstadualEditar;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeEditar;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfRgEditar;
    // End of variables declaration//GEN-END:variables
}
